umask 077
# Configurations
export DOT="$HOME/Library/Mobile Documents/com~apple~CloudDocs/dotfiles"
for file in $DOT/zsh/exports/*.sh; do source $file; done
for file in $DOT/zsh/plugins/*.sh; do source $file; done
for file in $DOT/zsh/aliases/*.sh; do source $file; done
source $ZSH/oh-my-zsh.sh
source $HOME/.local/.localenv.sh


# Plugins
plugins=(git)
# Miscellaneous configurations
eval "$(direnv hook zsh)"

# Automatically start tmux if not already in a tmux session
#if [ -z "$TMUX" ]; then
#  tmux a 2> /dev/null || tmux
#fi

# iTerm2 shell integration
[ -e "${HOME}.iterm2_shell_integration.zsh" ] && source "${HOME}/.iterm2_shell_integration.zsh"

git config --global pager.branch false
autoload -U +X compinit && compinit
compdef _terraform terraform
